name: polymer_demo
version: 0.0.1
description: An absolute bare-bones web app.
environment:
  sdk: '>=1.0.0 <2.0.0'
dependencies:
  browser: any
  core_elements: any
  paper_elements: any
  polymer: '>=0.15.1'
transformers:
- polymer:
    entry_points:
    - web/index.html
